//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Web.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_CHUNG_TU
    {
        public string MA_CHUNG_TU { get; set; }
        public string TEN_CHUNG_TU { get; set; }
        public string MA_LOAI_CHUNG_TU { get; set; }
        public string MA_CONG_TY { get; set; }
    
        public virtual CCTC_CONG_TY CCTC_CONG_TY { get; set; }
        public virtual DM_LOAI_CHUNG_TU DM_LOAI_CHUNG_TU { get; set; }
    }
}
