//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Web.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_DOI_TUONG
    {
        public DM_DOI_TUONG()
        {
            this.NGAN_HANG_CT_NTTK = new HashSet<NGAN_HANG_CT_NTTK>();
            this.NGAN_HANG_NTTK = new HashSet<NGAN_HANG_NTTK>();
            this.NGAN_HANG_UNC = new HashSet<NGAN_HANG_UNC>();
            this.NGAN_HANG_CT_UNC = new HashSet<NGAN_HANG_CT_UNC>();
            this.QUY_CT_PHIEU_CHI = new HashSet<QUY_CT_PHIEU_CHI>();
            this.QUY_PHIEU_CHI = new HashSet<QUY_PHIEU_CHI>();
            this.QUY_PHIEU_THU = new HashSet<QUY_PHIEU_THU>();
        }
    
        public string MA_DOI_TUONG { get; set; }
        public string TEN_DOI_TUONG { get; set; }
        public string DIA_CHI { get; set; }
        public string MA_LOAI_DOI_TUONG { get; set; }
        public string MA_CONG_TY { get; set; }
    
        public virtual CCTC_CONG_TY CCTC_CONG_TY { get; set; }
        public virtual DM_LOAI_DOI_TUONG DM_LOAI_DOI_TUONG { get; set; }
        public virtual ICollection<NGAN_HANG_CT_NTTK> NGAN_HANG_CT_NTTK { get; set; }
        public virtual ICollection<NGAN_HANG_NTTK> NGAN_HANG_NTTK { get; set; }
        public virtual ICollection<NGAN_HANG_UNC> NGAN_HANG_UNC { get; set; }
        public virtual ICollection<NGAN_HANG_CT_UNC> NGAN_HANG_CT_UNC { get; set; }
        public virtual ICollection<QUY_CT_PHIEU_CHI> QUY_CT_PHIEU_CHI { get; set; }
        public virtual ICollection<QUY_PHIEU_CHI> QUY_PHIEU_CHI { get; set; }
        public virtual ICollection<QUY_PHIEU_THU> QUY_PHIEU_THU { get; set; }
    }
}
