//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Web.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_KHACH_HANG
    {
        public DM_KHACH_HANG()
        {
            this.DM_LIEN_HE_KHACH_HANG = new HashSet<DM_LIEN_HE_KHACH_HANG>();
            this.DM_TK_NGAN_HANG_KH = new HashSet<DM_TK_NGAN_HANG_KH>();
        }
    
        public string MA_KHACH_HANG { get; set; }
        public string TEN_CONG_TY { get; set; }
        public string PHAN_LOAI_KHACH { get; set; }
        public string VAN_PHONG_GIAO_DICH { get; set; }
        public string DIA_CHI_XUAT_HOA_DON { get; set; }
        public string MST { get; set; }
        public string HOTLINE { get; set; }
        public string EMAIL { get; set; }
        public string FAX { get; set; }
        public string WEBSITE { get; set; }
        public string SALES_PHU_TRACH { get; set; }
        public string DIEU_KHOAN_THANH_TOAN { get; set; }
        public Nullable<int> SO_NGAY_DUOC_NO { get; set; }
        public Nullable<int> SO_NO_TOI_DA { get; set; }
        public string GHI_CHU { get; set; }
    
        public virtual DM_LOAI_KHACH DM_LOAI_KHACH { get; set; }
        public virtual HT_NGUOI_DUNG HT_NGUOI_DUNG { get; set; }
        public virtual ICollection<DM_LIEN_HE_KHACH_HANG> DM_LIEN_HE_KHACH_HANG { get; set; }
        public virtual ICollection<DM_TK_NGAN_HANG_KH> DM_TK_NGAN_HANG_KH { get; set; }
    }
}
