//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Web.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_LOAI_KHACH
    {
        public DM_LOAI_KHACH()
        {
            this.DM_KHACH_HANG = new HashSet<DM_KHACH_HANG>();
        }
    
        public string MA_LOAI_KHACH { get; set; }
        public string TEN_LOAI_KHACH { get; set; }
        public string DIEN_GIAI { get; set; }
    
        public virtual ICollection<DM_KHACH_HANG> DM_KHACH_HANG { get; set; }
    }
}
