//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Web.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_LOAI_NHA_CUNG_CAP
    {
        public DM_LOAI_NHA_CUNG_CAP()
        {
            this.DM_NHA_CUNG_CAP = new HashSet<DM_NHA_CUNG_CAP>();
        }
    
        public string MA_LOAI_NCC { get; set; }
        public string TEN_LOAI_NCC { get; set; }
        public string GHI_CHU { get; set; }
    
        public virtual ICollection<DM_NHA_CUNG_CAP> DM_NHA_CUNG_CAP { get; set; }
    }
}
