//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Web.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_LOAI_TK_NGAN_HANG
    {
        public DM_LOAI_TK_NGAN_HANG()
        {
            this.DM_TK_NGAN_HANG_NOI_BO = new HashSet<DM_TK_NGAN_HANG_NOI_BO>();
            this.DM_TK_NGAN_HANG_NCC = new HashSet<DM_TK_NGAN_HANG_NCC>();
            this.DM_TK_NGAN_HANG_KH = new HashSet<DM_TK_NGAN_HANG_KH>();
        }
    
        public string MA_LOAI { get; set; }
        public string TEN_LOAI { get; set; }
    
        public virtual ICollection<DM_TK_NGAN_HANG_NOI_BO> DM_TK_NGAN_HANG_NOI_BO { get; set; }
        public virtual ICollection<DM_TK_NGAN_HANG_NCC> DM_TK_NGAN_HANG_NCC { get; set; }
        public virtual ICollection<DM_TK_NGAN_HANG_KH> DM_TK_NGAN_HANG_KH { get; set; }
    }
}
