//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Web.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_NHOM_VTHH
    {
        public DM_NHOM_VTHH()
        {
            this.DM_HANG_HOA = new HashSet<DM_HANG_HOA>();
            this.DM_LOAI_HANG_CUNG_CAP = new HashSet<DM_LOAI_HANG_CUNG_CAP>();
            this.DM_NHA_CUNG_CAP = new HashSet<DM_NHA_CUNG_CAP>();
            this.DM_NHOM_VTHH1 = new HashSet<DM_NHOM_VTHH>();
            this.DM_TONKHO_HANG = new HashSet<DM_TONKHO_HANG>();
        }
    
        public string MA_NHOM_HANG_CHI_TIET { get; set; }
        public string CHUNG_LOAI_HANG { get; set; }
        public string MA_NHOM_HANG_CHA { get; set; }
        public string GHI_CHU { get; set; }
    
        public virtual ICollection<DM_HANG_HOA> DM_HANG_HOA { get; set; }
        public virtual ICollection<DM_LOAI_HANG_CUNG_CAP> DM_LOAI_HANG_CUNG_CAP { get; set; }
        public virtual ICollection<DM_NHA_CUNG_CAP> DM_NHA_CUNG_CAP { get; set; }
        public virtual ICollection<DM_NHOM_VTHH> DM_NHOM_VTHH1 { get; set; }
        public virtual DM_NHOM_VTHH DM_NHOM_VTHH2 { get; set; }
        public virtual ICollection<DM_TONKHO_HANG> DM_TONKHO_HANG { get; set; }
    }
}
