//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Web.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_NHA_CUNG_CAP
    {
        public DM_NHA_CUNG_CAP()
        {
            this.DM_LIEN_HE_NHA_CUNG_CAP = new HashSet<DM_LIEN_HE_NHA_CUNG_CAP>();
            this.DM_LOAI_HANG_CUNG_CAP = new HashSet<DM_LOAI_HANG_CUNG_CAP>();
            this.DM_TK_NGAN_HANG_NCC = new HashSet<DM_TK_NGAN_HANG_NCC>();
            this.QUY_CT_PHIEU_CHI = new HashSet<QUY_CT_PHIEU_CHI>();
        }
    
        public string MA_NHA_CUNG_CAP { get; set; }
        public string TEN_NHA_CUNG_CAP { get; set; }
        public string PHAN_LOAI_NCC { get; set; }
        public string LOAI_HANG_CUNG_CAP { get; set; }
        public string VAN_PHONG_GIAO_DICH { get; set; }
        public string DIA_CHI_XUAT_HOA_DON { get; set; }
        public string MST { get; set; }
        public string SDT { get; set; }
        public string EMAIL { get; set; }
        public string FAX { get; set; }
        public string WEBSITE { get; set; }
        public string MUA_HANG_PHU_TRACH { get; set; }
        public string DIEU_KHOAN_THANH_TOAN { get; set; }
        public Nullable<int> SO_NGAY_DUOC_NO { get; set; }
        public Nullable<int> SO_NO_TOI_DA { get; set; }
        public string DANH_GIA { get; set; }
        public string GHI_CHU { get; set; }
    
        public virtual ICollection<DM_LIEN_HE_NHA_CUNG_CAP> DM_LIEN_HE_NHA_CUNG_CAP { get; set; }
        public virtual ICollection<DM_LOAI_HANG_CUNG_CAP> DM_LOAI_HANG_CUNG_CAP { get; set; }
        public virtual DM_LOAI_NHA_CUNG_CAP DM_LOAI_NHA_CUNG_CAP { get; set; }
        public virtual DM_NHOM_VTHH DM_NHOM_VTHH { get; set; }
        public virtual HT_NGUOI_DUNG HT_NGUOI_DUNG { get; set; }
        public virtual ICollection<DM_TK_NGAN_HANG_NCC> DM_TK_NGAN_HANG_NCC { get; set; }
        public virtual ICollection<QUY_CT_PHIEU_CHI> QUY_CT_PHIEU_CHI { get; set; }
    }
}
